version: '3.4'

services:
  webservice:
    image: dev/devpi
    build:
      context: ./docker
      dockerfile: Dockerfile
    env_file:
      - .env.local
    ports:
      - 3141:3141
      - 80:80
    volumes:
      - ./data:/data
